### PR TITLE
Add rtc support

### PR DESCRIPTION
**Pull request by mdrobnak**
This PR adds RTC support for the stm32f7 series SoCs. This is based on the stm32f3 code by @David-OConnor, and ST reference examples. Set and get of time, and individual hour/minute/second/day/month/year all tested successfully. Have not tested full date set, but uses the same code and should work fine.

### CODE REVIEW

**Comment by mdrobnak** [comment]
Please note this code is tested and working on an ST Nucleo F767ZI board. @mvertescher what do I need to do in order to get this merged in?

**Review by hannobraun — APPROVED** [review]
I took a quick look. I didn't test myself, nor do a thorough review against the reference manual, but I don't see anything wrong here.

Looks good to me!

**Comment by hannobraun** [comment]
(Not merging right now in case @mvertescher wants to take a look. Feel free to ping me if nothing happens for a while, @mdrobnak.)

**Review by mvertescher — APPROVED** [review]
Nice, looks good!

**Comment by mvertescher** [comment]
This impl seems fine to me. I haven't tested on hardware yet, but I plan on it. An example showing how to use the RTC API might be a useful addition in the future. Thanks for this feature @mdrobnak!

**Pull request merged**
