### PR TITLE
Upgrade rand crate

### PR DESCRIPTION
**Pull request by dutchmartin**
Also, maybe it is smart to setup something like [dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically) so dependencies kee being updated.

### CODE REVIEW

**Review by hannobraun — APPROVED** [review]
Thank you, @dutchmartin!

I've opened #119 to track your suggestion of setting up dependabot.

**Comment by dutchmartin** [comment]
Thanks for merging, would you mind releasing a new hal verison with this?

**Comment by hannobraun** [comment]
Can do. I've added it to my task list. I'll try to get to it soon.

**Comment by hannobraun** [comment]
@dutchmartin I figured it would be good to fix the CI build before releasing. This turned into a bit of a project, as you can see from the pull requests I submitted. I hope to get those merged within the next 1-2 weeks.

Are you in a hurry regarding the release? If so, I'd be happy to release as-is. My fixes should be pretty low-impact, so it's not essential to get them into the next release.

**Comment by dutchmartin** [comment]
@hannobraun It can wait. I’ve used this crate in my internship project, but I’ve finished that last week, so I do not have acces to the code nor devboard anymore :(
But thank you for maintaining this great crate!!!

**Comment by hannobraun** [comment]
New release is out!

**Pull request merged**
