### PR TITLE
Fix LCD timings for F746G disco example

### PR DESCRIPTION
**Pull request by mchodzikiewicz**
This PR fixes https://github.com/stm32-rs/stm32f7xx-hal/issues/105

### CODE REVIEW

**Comment by mchodzikiewicz** [comment]
btw, timings are adjusted according to official ST example: https://github.com/STMicroelectronics/STM32CubeF7/tree/master/Drivers/BSP/STM32746G-Discovery

**Comment by hannobraun** [comment]
I haven't used this feature, nor do I have the hardware to test it. @grodino, it seems you added that code, any thoughts?

**Comment by grodino** [comment]
@mchodzikiewicz The values I used were taken from an Application Note from ST and worked for me but if this is from the official example, I'm fine with this too ;)
@hannobraun I do not have the hardware anymore so I can't test it sorry

**Comment by hannobraun** [comment]
Okay then, since it works for @mchodzikiewicz and nobody objects, I'm merging. Thank you @mchodzikiewicz and @grodino!

**Comment by mchodzikiewicz** [comment]
great! What I can tell is that my two boards are from different hw revisions (B-02 and B-04) and both of them did not worked and started working after this adjustment

**Pull request merged**
