### PR TITLE
Add USB driver for OTG_HS

### PR DESCRIPTION
**Pull request by Disasm**
Based on the code from the [usb_midi](https://github.com/perlindgren/stm32f7xx-hal/tree/usb_midi) branch by @perlindgren.

### CODE REVIEW

**Review by perlindgren — APPROVED** [review]
Look excellent. 
```
    /// Call `UsbBus::new` to construct and initialize the USB peripheral driver.
    pub fn new(
```
Maybe it should be noted that the external Phy needs to be initialized.

**Comment by Disasm** [comment]
As long as we usually force user to reconfigure all the required pins into appropriate AFs and pass them to driver, I think that external PHY case will be handled in a separate constructor function. I still have to figure out an interface for this.

**Comment by Disasm** [comment]
Well, I tested this PR on a F723 Discovery board and everything works (apart from the usbd-serial compliance issue). I decided to leave the UPLI PHY support for now. I have a board with an external PHY, but it's a F407 board, so I'm going to add external PHY support to `stm32f4xx-hal` first and then maybe we port it to `stm32f7xx-hal`.

Ready for review.

**Comment by Disasm** [comment]
Also do we want to make the `synopsys-usb-otg` dependency non-optional like it was done for `stm32-fmc`? It has a nice build time of 4-5s (most of which is `cortex-m` and its deps) and only 3 dependencies.

**Comment by hannobraun** [comment]
As usual, I don't have the time for anything substantial, but I did a cursory review and this looks good. Merging, since @Disasm successfully tested it and this hasn't received any negative feedback.

Thank you, @Disasm!

**Comment by Disasm** [comment]
@hannobraun thank you!

**Pull request merged**
