### PR TITLE
Solve bug when requesting higher clock frequencies

### PR DESCRIPTION
**Pull request by ingegus**
2 modifications :
* PLLN and PLLP are chosen in order to minimise the error between the requested clock and the final clock
* The flash wait states are adjusted before the pll is choosen

### CODE REVIEW

**Comment by mvertescher** [comment]
Nice! Mind squashing and rebasing your commits @ingegus ?

**Comment by ingegus** [comment]
Ok but what do you mean by squashing and rebasing ? (I am not used to contributing nor working with git) 
Is this something like that : https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/ ?

**Comment by ingegus** [comment]
I think it's ok now

**Comment by mvertescher** [comment]
Awesome, thanks for fixing this!

**Pull request merged**
