### PR TITLE
[#79] Add UART5 for STM32F723E DISCO

### LINKED ISSUE #79: UART5 is missing
To me it looks like UART5 is missing:

~~~rust
#[cfg(any(feature = "device-selected",))]
impl_instance! {
    USART1: (apb2enr, usart1sel, usart1en),
    USART2: (apb1enr, usart2sel, usart2en),
    USART3: (apb1enr, usart3sel, usart3en),
    UART4:  (apb1enr, uart4sel,  uart4en),
    USART6: (apb2enr, usart6sel, usart6en),
    UART7:  (apb1enr, uart7sel,  uart7en),
}
~~~

### PR DESCRIPTION
**Pull request by ctron**
closes #79

### CODE REVIEW

**Comment by ctron** [comment]
@bbrown1867 @mvertescher Is there something wrong with the PR? Or any other reason not to review or merge this?

**Comment by bbrown1867** [comment]
> @bbrown1867 @mvertescher Is there something wrong with the PR? Or any other reason not to review or merge this?

Looks good to me, but I am not a maintainer so I can't approve it. My guess is maintainers just haven't gotten around to looking at it.

**Review by mvertescher — APPROVED** [review]
Cool, LGTM!

**Comment by mvertescher** [comment]
> @bbrown1867 @mvertescher Is there something wrong with the PR? Or any other reason not to review or merge this?
Nope, looks good!

**Pull request merged**
