### PR TITLE
Better consistency with STM32F4XX-HAL

### PR DESCRIPTION
**Pull request by no111u3**
Change `device` to `pac` and update library, examples code too.

### CODE REVIEW

**Comment by rfuest** [comment]
The other stm32 hal crates have recently switched to use `pac` instead of `stm32`:
https://github.com/stm32-rs/stm32f4xx-hal/commit/b53be6c1b628ef82e3d852d5c2fda0d8e825f24d
https://github.com/stm32-rs/stm32f1xx-hal/pull/196

**Comment by mvertescher** [comment]
@no111u3 could we switch over to using `pac` instead of `stm32`?

**Comment by no111u3** [comment]
@mvertescher - I updated this commit from `device` to `pac`.

**Comment by rfuest** [comment]
@no111u3 Did you forget to commit the changes before pushing the branch again? Because the latest commit in your branch still seems to use `stm32` instead of `pac`.

**Comment by no111u3** [comment]
> @no111u3 Did you forget to commit the changes before pushing the branch again? Because the latest commit in your branch still seems to use `stm32` instead of `pac`.

Sorry, sure. I forgot about update commit ..

**Comment by mvertescher** [comment]
Awesome, thanks for update @no111u3!

**Pull request merged**
