### PR TITLE
Add initial PWM support

### PR DESCRIPTION
**Pull request by maximeborges**
The main purpose of this PR is to get some initial support for PWM.
It also integrates some features for timers from the `stm32f4xx-hal` repo.
This will break existing implementation, but get us an much cleaner interface for instantiating and using timers.

### CODE REVIEW

**Comment by hannobraun** [comment]
Thank you for the pull request, @maximeborges! I'll try to find the time to review it soon. I *hope* that will be next week, but no promises.

Please note that I'm stepping down as a maintainer and haven't found a replacement yet. If you're interested in getting involved, please check out issue #165.

**Comment by maximeborges** [comment]
This seems to be working only on the first channel of each timer for some reason...

**Comment by hannobraun** [comment]
Sorry, I haven't gotten to those pull requests yet. I'm hoping for next week.

**Comment by maximeborges** [comment]
I'm currently cleaning up a demo project using another version based on the H7 version, which support advanced features that I needed.

**Review by hannobraun — CHANGES_REQUESTED** [review]
Thanks again, @maximeborges. I couldn't find the time for a proper review, but I managed to take a look, and this looks good.

The CI build fails though, due to formatting (running `cargo fmt` should fix that, as long as rustfmt is installed) and because this broke `examples/stm32f7disco-screen/screen.rs`.

Once CI is green, I'd be happy to merge.

**Comment by hannobraun** [comment]
Thank you for the changes, @maximeborges. There's still a CI failure, unfortunately. This time a problem with the F722.

**Comment by maximeborges** [comment]
Replaced by #179

**Pull request closed without merging**
