### PR TITLE
allow to configure:

### PR DESCRIPTION
**Pull request by msmouni**
+UsartInversion
+WordLength
+ParityControl

### CODE REVIEW

**Comment by hannobraun** [comment]
Hi @msmouni, please be aware that this repository is unmaintained, and I won't merge any new pull requests. Please check out https://github.com/stm32-rs/stm32f7xx-hal/issues/165, if you want to help out.

**Comment by msmouni** [comment]
thank you for all the effort you invested in developing this crate, and good luck for your future projects

**Comment by hannobraun** [comment]
Thank you!

**Comment by maximeborges** [comment]
Reimplemented in #203

**Pull request closed without merging**
